name: animation_director
description: AnimationDirector is a package to create beautiful and smooth animations for flutter framework
version: 0.1.1
homepage: https://github.com/Ali-Azmoud/animation_director

environment:
  sdk: ">=2.3.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
